export const ADD_PROJECT = 'ADD_PROJECT';
export const DELETE_PROJECT_MUTATION = 'DELETE_PROJECT_MUTATION';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const DEFINE_PROJECTS = 'DEFINE_PROJECTS';

export const ADD_TASK = 'ADD_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const EDIT_TASK = 'EDIT_TASK';
export const DEFINE_TASKS = 'DEFINE_PROJECT'

export const NOTIFICATE = 'NOTIFICATE';